#FROM arm32v7/python
FROM arm32v7/debian

RUN apt-get update -y && \
    apt-get install -y patch python-jsonrpclib python-opencv python-pil python-zbar

ADD qr2mopidy.py /

COPY headers.patch /
RUN patch /usr/share/pyshared/jsonrpclib/jsonrpc.py headers.patch

CMD [ "python", "/qr2mopidy.py" ]
